FROM python:3.12-slim

WORKDIR /app

# dependencias del sistema (útiles para dbt + builds)
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# por defecto entra en bash para poder ejecutar dbt
CMD ["bash"]