FROM python:3.12-slim

WORKDIR /app

# dependencias del sistema (útiles para dbt + builds)
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    git \
    wget \
    unzip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# instalar duckdb CLI
RUN wget https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip \
    && unzip duckdb_cli-linux-amd64.zip \
    && chmod +x duckdb \
    && mv duckdb /usr/local/bin/ \
    && rm duckdb_cli-linux-amd64.zip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# por defecto entra en bash para poder ejecutar dbt
CMD ["bash"]